# Generated by Django 3.1.3 on 2021-03-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210326_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
