# Generated by Django 3.1.3 on 2021-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210326_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
