# Generated by Django 3.1.3 on 2021-03-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210327_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/sub-category-image'),
        ),
    ]
