# Generated by Django 3.1.3 on 2021-03-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_subcategory_sub_cat_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
