# Generated by Django 3.1.3 on 2021-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='l_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='s_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
