# Generated by Django 3.1.3 on 2021-03-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='send_on',
            new_name='sent_on',
        ),
    ]
